# site settings
title: SOTER
subtitle: "Seguridad laboral"
description: "Bienvenidos a nuestra empresa especializada en Seguridad y Salud en el Trabajo (SST) y Ambiente. Somos un equipo de profesionales comprometidos con la protección del medio ambiente y la promoción de entornos laborales seguros y sostenibles."
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Victoria Cruz

# contact information
email: infosotersas@gmail.com

contacts:
- street_address: "Puente Aranda, Bogotá, Cundinamarca"
  whatsapp_display: +57 (315) 511-3610
  whatsapp: 573155113610 
  
- street_address: "San Francisco, Bucaramanga, Santander"
  whatsapp_display: "+57 (316) 500-2431"
  whatsapp: 573165002431

footer_text: "Contamos con una amplia experiencia trabajando con organizaciones de diversos sectores para garantizar el cumplimiento de regulaciones ambientales y promover una cultura de prevención de riesgos laborales. No dude en ponerse en contacto con nosotros para obtener"

footer_text_bold: "una revisión gratuita que cumple con los estándares mínimos establecidos en la resolución 0312/2019."

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
instagram_display: "@sotersas"
instagram: https://www.instagram.com/sotersas/

#socials:
#  gitHub: 
#  gitLab:
#  google-Plus: 
#  instagram: https://www.instagram.com/sotersas/
#  linkedIn: 
#  twitter: 
#  facebook: 


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
